import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { TerminalProtocolTag } from "./TerminalProtocolTag";
const state = vi.hoisted(() => ({ enabled: true, unread: false, focus: vi.fn() }));
vi.mock("./TerminalNotificationProvider", () => ({ useTerminalNotifications: () => ({ enabled: state.enabled, unread: () => state.unread }) }));
vi.mock("../terminalViewRegistry", () => ({ focusTerminalBlock: state.focus }));
beforeEach(() => { state.enabled = true; state.unread = false; vi.clearAllMocks(); });
afterEach(cleanup);
it("combines enabled protocols in one compact hover tooltip and hides disabled ones", () => {
  const view = render(<TerminalProtocolTag blockId="b" connected directoryState="ready"/>);
  expect(screen.getAllByRole("button")).toHaveLength(1);
  expect(screen.getByRole("button")).toHaveTextContent("osc");
  expect(screen.queryByRole("tooltip")).not.toBeInTheDocument();
  fireEvent.mouseEnter(screen.getByRole("button"));
  const tooltip = screen.getByRole("tooltip");
  for (const name of ["OSC 7", "BEL", "OSC 9", "OSC 777"]) expect(tooltip).toHaveTextContent(name);
  expect(tooltip).toHaveTextContent("同步当前目录");
  fireEvent.mouseLeave(screen.getByRole("button"));
  expect(screen.queryByRole("tooltip")).not.toBeInTheDocument();
  state.enabled = false;
  view.rerender(<TerminalProtocolTag blockId="b" connected directoryState="waiting"/>);
  fireEvent.focus(screen.getByRole("button"));
  expect(screen.getByRole("tooltip")).toHaveTextContent("等待目录上报");
  expect(screen.getByRole("tooltip")).not.toHaveTextContent("BEL");
  fireEvent.keyDown(screen.getByRole("button"), { key: "Escape" });
  expect(screen.queryByRole("tooltip")).not.toBeInTheDocument();
  view.rerender(<TerminalProtocolTag blockId="b" connected/>);
  expect(screen.queryByRole("button")).not.toBeInTheDocument();
});
it("keeps notification-only mode and unread source focusing without requiring OSC 7", () => {
  state.unread = true;
  const view = render(<TerminalProtocolTag blockId="b" connected/>);
  expect(screen.getByRole("button")).toHaveAttribute("data-state", "unread");
  fireEvent.mouseEnter(screen.getByRole("button"));
  expect(screen.queryByText("OSC 7", { selector: "strong" })).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole("button"));
  expect(state.focus).toHaveBeenCalledWith("b");
  view.rerender(<TerminalProtocolTag blockId="b" connected={false} directoryState="ready"/>);
  expect(screen.queryByRole("button")).not.toBeInTheDocument();
  expect(screen.queryByRole("tooltip")).not.toBeInTheDocument();
  view.rerender(<TerminalProtocolTag blockId="b" connected/>);
  expect(screen.queryByRole("tooltip")).not.toBeInTheDocument();
});
