import type * as Desktop from "../../lib/tauri/git";
import { demoGitAction, demoGitDiff, demoGitSnapshot } from "../demoGitAdapter";
import { featureTarget, openFeatureSession } from "../featureSessions";
import { getDemoProject } from "../demoProject";
import { DEMO_HOME } from "../fixtures";
export type * from "../../lib/tauri/git";

export const gitAvailable: typeof Desktop.gitAvailable = async () => true;
export const selectGitRepositoryDirectory: typeof Desktop.selectGitRepositoryDirectory = async () => DEMO_HOME;
export const loadGitSnapshot: typeof Desktop.loadGitSnapshot = async path => demoGitSnapshot(null, path);
export const stageGitPaths: typeof Desktop.stageGitPaths = async (repository, paths) => demoGitAction(null, { type: "stage", repository, paths });
export const stageAllGitChanges: typeof Desktop.stageAllGitChanges = async repository => demoGitAction(null, { type: "stageAll", repository });
export const unstageGitPaths: typeof Desktop.unstageGitPaths = async (repository, paths) => demoGitAction(null, { type: "unstage", repository, paths });
export const unstageAllGitChanges: typeof Desktop.unstageAllGitChanges = async repository => demoGitAction(null, { type: "unstageAll", repository });
export const commitGitChanges: typeof Desktop.commitGitChanges = async (repository, message) => demoGitAction(null, { type: "commit", repository, message });
export const loadGitChangeDiff: typeof Desktop.loadGitChangeDiff = async (repository, path, staged) => demoGitDiff(null, repository, path, staged);
export const connectGitSession: typeof Desktop.connectGitSession = async (input, event) => openFeatureSession("git", input.profileId, event);
export const executeRemoteGit: typeof Desktop.executeRemoteGit = async (id, target, action) => demoGitAction(featureTarget(id, "git", target), action);
export const loadRemoteGitChangeDiff: typeof Desktop.loadRemoteGitChangeDiff = async (id, target, repository, path, staged) => demoGitDiff(featureTarget(id, "git", target), repository, path, staged);
export const listRemoteGitDirectory: typeof Desktop.listRemoteGitDirectory = async (id, target, input) => {
  const project = getDemoProject(featureTarget(id, "git", target)); const path = project.resolve(DEMO_HOME, input);
  return { path, entries: project.list(path).filter(entry => entry.isDirectory).map(entry => ({ ...entry, isSymlink: false, modifiedAt: null, permissionMode: 493 })) };
};
export const gitError: typeof Desktop.gitError = error => {
  if (typeof error === "object" && error !== null && "code" in error && "message" in error && typeof error.code === "string" && typeof error.message === "string") return { code: error.code, message: error.message };
  return { code: "demoUnsupported", message: error instanceof Error ? error.message : String(error) };
};
const unavailable = async (): Promise<never> => { throw new Error("此 Git 操作尚未模拟；可体验差异、暂存、取消暂存和提交。"); };
export const fetchGitRepository: typeof Desktop.fetchGitRepository = async repository => demoGitSnapshot(null, repository);
export const pullGitRepository: typeof Desktop.pullGitRepository = unavailable;
export const pushGitRepository: typeof Desktop.pushGitRepository = unavailable;
export const initializeGitRepository: typeof Desktop.initializeGitRepository = unavailable;
export const initializeGitSubmodule: typeof Desktop.initializeGitSubmodule = unavailable;
export const checkoutGitSubmodule: typeof Desktop.checkoutGitSubmodule = unavailable;
export const discardGitPaths: typeof Desktop.discardGitPaths = unavailable;
export const loadGitCommitFiles: typeof Desktop.loadGitCommitFiles = unavailable;
export const loadGitCommitFileDiff: typeof Desktop.loadGitCommitFileDiff = unavailable;
export const loadGitConflictDetail: typeof Desktop.loadGitConflictDetail = unavailable;
export const resolveGitConflict: typeof Desktop.resolveGitConflict = unavailable;
export const createGitBranch: typeof Desktop.createGitBranch = unavailable;
export const createGitBranchFrom: typeof Desktop.createGitBranchFrom = unavailable;
export const createGitBranchFromCommit: typeof Desktop.createGitBranchFromCommit = unavailable;
export const renameGitBranch: typeof Desktop.renameGitBranch = unavailable;
export const deleteGitBranch: typeof Desktop.deleteGitBranch = unavailable;
export const switchGitBranch: typeof Desktop.switchGitBranch = unavailable;
export const trackGitRemoteBranch: typeof Desktop.trackGitRemoteBranch = unavailable;
export const mergeGitBranch: typeof Desktop.mergeGitBranch = unavailable;
export const continueGitMerge: typeof Desktop.continueGitMerge = unavailable;
export const abortGitMerge: typeof Desktop.abortGitMerge = unavailable;
export const loadRemoteGitCommitFiles: typeof Desktop.loadRemoteGitCommitFiles = unavailable;
export const loadRemoteGitCommitFileDiff: typeof Desktop.loadRemoteGitCommitFileDiff = unavailable;
export const loadRemoteGitConflictDetail: typeof Desktop.loadRemoteGitConflictDetail = unavailable;
export const resolveRemoteGitConflict: typeof Desktop.resolveRemoteGitConflict = unavailable;
